---
version: "3.1"
services:
  grocer:
    image: dfialho14/grocer
    container_name: grocer
    user: 1500:1500
    environment:
      QUARKUS_DATASOURCE_USERNAME: "postgres"
      QUARKUS_DATASOURCE_PASSWORD: "postgres"
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/grocer"
      GROCER_CONTINENTEONLINE_DIRECTORY: "/continenteonline"
    volumes:
      - /home/dfialho/Downloads/grocer:/continenteonline
    restart: unless-stopped

  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grocer
    ports:
      - "5432:5432"
    restart: unless-stopped
